#!/usr/bin/env python3
"""Regenerate all genesis-bound PQBTC SHRINCS transaction vectors.

The script uses the exact pinned executable SHRINCS draft to create the
stateful and stateless signatures, while the project-owned transaction model
creates the chain-separated digest.  It rewrites:

* ``contrib/shrincs-tx/vector.json``;
* ``src/test/shrincs_tx_v0_signed_seam_vectors.h``;
* the exact digest constants in ``src/test/shrincs_tx_v0_tests.cpp``.

No secret key or seed is written to the repository.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import subprocess
import sys
from types import ModuleType
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = ROOT / "contrib/shrincs-tx/tx_model.py"
DESIGN_VECTOR_PATH = ROOT / "contrib/shrincs-tx/vector.json"
SIGNED_HEADER_PATH = ROOT / "src/test/shrincs_tx_v0_signed_seam_vectors.h"
CPP_TEST_PATH = ROOT / "src/test/shrincs_tx_v0_tests.cpp"
DRAFT_COMMIT = "acc6bda51dc3b94848d118967247ad0f3cd7a80e"
EXPECTED_CHAIN_DOMAIN = "db0e425cda8dcebc9e64203d2a5dfde2e954954f3dc95b8b9807590103d07652"


class VectorError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VectorError(message)


def load_module(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    require(spec is not None and spec.loader is not None, f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    assert spec is not None and spec.loader is not None
    spec.loader.exec_module(module)
    return module


def git_head(path: Path) -> str:
    return subprocess.run(
        ["git", "-C", str(path), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def kdf(label: bytes, length: int) -> bytes:
    output = bytearray()
    counter = 0
    while len(output) < length:
        output.extend(hashlib.sha256(label + counter.to_bytes(4, "big")).digest())
        counter += 1
    return bytes(output[:length])


def cpp_string(name: str, value: str, width: int = 96) -> str:
    chunks = [value[index : index + width] for index in range(0, len(value), width)] or [""]
    body = "\n".join(f'    "{chunk}"' for chunk in chunks)
    return f"inline constexpr std::string_view {name}{{\n{body}}};\n"


def signed_header(payload: dict[str, str]) -> str:
    ordered = (
        "PUBLIC_KEY_HEX",
        "PUBLIC_KEY_SHA256_HEX",
        "CHAIN_ID_HEX",
        "CONTEXT_HEX",
        "OUTPUT_COMMITMENT_HEX",
        "TRANSACTION_DIGEST_HEX",
        "STRIPPED_TRANSACTION_HEX",
        "STATEFUL_SIGNATURE_SHA256_HEX",
        "STATEFUL_SIGNATURE_HEX",
        "STATELESS_SIGNATURE_SHA256_HEX",
        "STATELESS_SIGNATURE_HEX",
    )
    constants = "\n".join(cpp_string(name, payload[name]) for name in ordered)
    return f'''// Copyright (c) 2026 The PQBTC Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit/.
//
// Generated by contrib/shrincs-tx/generate_shrincslab_vectors.py.
// Do not edit by hand.

#ifndef BITCOIN_TEST_SHRINCS_TX_V0_SIGNED_SEAM_VECTORS_H
#define BITCOIN_TEST_SHRINCS_TX_V0_SIGNED_SEAM_VECTORS_H

#include <string_view>

namespace shrincs_tx_v0_signed_seam_vectors {{

{constants}

}} // namespace shrincs_tx_v0_signed_seam_vectors

#endif // BITCOIN_TEST_SHRINCS_TX_V0_SIGNED_SEAM_VECTORS_H
'''


def replace_regex(text: str, pattern: str, replacement: str, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise VectorError(f"expected exactly one {label} replacement, got {count}")
    return updated


def patch_cpp_test(
    design: dict[str, Any],
    signed: dict[str, str],
    mutation_digests: dict[str, str],
) -> None:
    text = CPP_TEST_PATH.read_text(encoding="utf-8")

    for name, digest in mutation_digests.items():
        pattern = rf'(\{{"{re.escape(name)}", ")[0-9a-f]{{64}}("\}},)'
        text = replace_regex(text, pattern, rf"\g<1>{digest}\g<2>", f"mutation {name}")

    text = replace_regex(
        text,
        r'BOOST_CHECK\(test_case\.chain_id == RawUint256\("[0-9a-f]{64}"\)\);',
        f'BOOST_CHECK(test_case.chain_id == RawUint256("{design["chain_id"]}"));',
        "chain domain",
    )
    text = replace_regex(
        text,
        r'BOOST_CHECK_EQUAL\(RawHex\(RequireDigest\(test_case\)\), "[0-9a-f]{64}"\);',
        f'BOOST_CHECK_EQUAL(RawHex(RequireDigest(test_case)), "{design["input_digests"][0]}");',
        "design input 0 digest",
    )
    text = replace_regex(
        text,
        r'BOOST_CHECK_EQUAL\(RawHex\(RequireDigest\(second_input\)\), "[0-9a-f]{64}"\);',
        f'BOOST_CHECK_EQUAL(RawHex(RequireDigest(second_input)), "{design["input_digests"][1]}");',
        "design input 1 digest",
    )
    text = replace_regex(
        text,
        r'BOOST_CHECK_EQUAL\(RawHex\(RequireDigest\(signed_case\)\), "[0-9a-f]{64}"\);',
        f'BOOST_CHECK_EQUAL(RawHex(RequireDigest(signed_case)), "{signed["TRANSACTION_DIGEST_HEX"]}");',
        "signed digest",
    )
    CPP_TEST_PATH.write_text(text, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--shrincs-bip", type=Path, required=True)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    require(git_head(args.shrincs_bip) == DRAFT_COMMIT, "upstream draft commit drifted")
    model = load_module(MODEL_PATH, "pqbtc_shrincslab_tx_model")
    reference = load_module(args.shrincs_bip / "impl/shrincs.py", "pqbtc_shrincslab_reference")
    require(model.TEST_CHAIN_ID.hex() == EXPECTED_CHAIN_DOMAIN, "chain domain drifted")

    design = model.vector_payload()
    DESIGN_VECTOR_PATH.write_text(
        json.dumps(design, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    seed = kdf(b"pqbtc-shrincs-tx-v0/seam/seed", 48)
    structure = bytes([reference.FXMSS_SHAPE_UNBALANCED, 4])
    secret_key, public_key = reference.shrincs_keygen(seed, structure)
    require(len(public_key) == model.PUBLIC_KEY_BYTES, "public-key size drifted")

    tx = model.build_design_transaction(public_key)
    digest = model.transaction_sighash(tx, 0, model.TEST_CHAIN_ID)
    stateful = reference.shrincs_sign(
        digest,
        model.SHRINCS_CONTEXT,
        secret_key,
        0,
        None,
    )
    stateless = reference.shrincs_sign(
        digest,
        model.SHRINCS_CONTEXT,
        secret_key,
        None,
        kdf(b"pqbtc-shrincs-tx-v0/seam/stateless-randomizer", 16),
    )
    require(stateful is not None and len(stateful) == model.STATEFUL_SIGNATURE_MIN, "stateful signing drifted")
    require(stateless is not None and len(stateless) == model.STATELESS_SIGNATURE_BYTES, "stateless signing drifted")
    require(reference.shrincs_verify(digest, stateful, model.SHRINCS_CONTEXT, public_key), "stateful self-verification failed")
    require(reference.shrincs_verify(digest, stateless, model.SHRINCS_CONTEXT, public_key), "stateless self-verification failed")

    signed = {
        "PUBLIC_KEY_HEX": public_key.hex(),
        "PUBLIC_KEY_SHA256_HEX": hashlib.sha256(public_key).hexdigest(),
        "CHAIN_ID_HEX": model.TEST_CHAIN_ID.hex(),
        "CONTEXT_HEX": model.SHRINCS_CONTEXT.hex(),
        "OUTPUT_COMMITMENT_HEX": model.output_commitment(public_key).hex(),
        "TRANSACTION_DIGEST_HEX": digest.hex(),
        "STRIPPED_TRANSACTION_HEX": tx.serialize_stripped().hex(),
        "STATEFUL_SIGNATURE_SHA256_HEX": hashlib.sha256(stateful).hexdigest(),
        "STATEFUL_SIGNATURE_HEX": stateful.hex(),
        "STATELESS_SIGNATURE_SHA256_HEX": hashlib.sha256(stateless).hexdigest(),
        "STATELESS_SIGNATURE_HEX": stateless.hex(),
    }
    SIGNED_HEADER_PATH.write_text(signed_header(signed), encoding="utf-8")

    mutation_digests = {
        name: model.transaction_sighash(candidate, 0, model.TEST_CHAIN_ID).hex()
        for name, candidate in model.transaction_surface_mutations(tx=model.build_design_transaction(bytes(range(model.PUBLIC_KEY_BYTES)))).items()
    }
    require(len(mutation_digests) == 22, "mutation corpus drifted")
    patch_cpp_test(design, signed, mutation_digests)

    result = {
        "result": "PASS",
        "draft_commit": DRAFT_COMMIT,
        "chain_domain": model.TEST_CHAIN_ID.hex(),
        "transaction_digest": digest.hex(),
        "public_key_sha256": signed["PUBLIC_KEY_SHA256_HEX"],
        "stateful_signature_bytes": len(stateful),
        "stateful_signature_sha256": signed["STATEFUL_SIGNATURE_SHA256_HEX"],
        "stateless_signature_bytes": len(stateless),
        "stateless_signature_sha256": signed["STATELESS_SIGNATURE_SHA256_HEX"],
        "mutation_vectors": len(mutation_digests),
    }
    print(json.dumps(result, sort_keys=True) if args.json else json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
