name: test each commit

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-each-commit:
    name: 'test each commit'
    runs-on: ubuntu-24.04
    timeout-minutes: 360
    env:
      MAX_COUNT: 6
    steps:
      - name: Determine fetch depth
        run: echo "FETCH_DEPTH=8" >> "$GITHUB_ENV"

      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Determine commit range
        run: |
          git checkout HEAD~
          MERGE_BASE=$(git rev-list -n1 --merges HEAD)
          EXCLUDE_MERGE_BASE_ANCESTORS=
          if test -n "$MERGE_BASE"; then
            EXCLUDE_MERGE_BASE_ANCESTORS=^${MERGE_BASE}^@
          fi
          echo "TEST_BASE=$(git rev-list -n$((${{ env.MAX_COUNT }} + 1)) --reverse HEAD $EXCLUDE_MERGE_BASE_ANCESTORS | head -1)" >> "$GITHUB_ENV"

      - name: Prepare merge base and toolchain
        run: |
          git fetch origin main
          git config user.email "ci@example.com"
          git config user.name "CI"
          sudo apt-get update
          sudo apt-get install clang mold ccache build-essential cmake ninja-build pkgconf python3-zmq libevent-dev libboost-dev libsqlite3-dev systemtap-sdt-dev libzmq3-dev qt6-base-dev qt6-tools-dev qt6-l10n-tools libqrencode-dev capnproto libcapnp-dev -y
          sudo pip3 install --break-system-packages pycapnp

      - name: Compile and run tests
        run: |
          git rebase --exec "git merge --no-commit origin/main && python3 ./.github/ci-test-each-commit-exec.py && git reset --hard" ${{ env.TEST_BASE }}
